log_format json_threatintel escape=json
  '{'
    '"timestamp":"$time_iso8601",'
    '"ip":"$remote_addr",'
    '"method":"$request_method",'
    '"url":"$request_uri",'
    '"status":"$status",'
    '"referer":"$http_referer",'
    '"user_agent":"$http_user_agent",'
    '"x_forwarded_for":"$http_x_forwarded_for"'
  '}';
