# Stage 1: Build da Nexus
FROM node:22-alpine AS build

ARG NPM_VERSION
ARG NPM_REGISTRY_URI

# Variabili Vite necessarie al build time
ARG VITE_APP_TITLE
ARG VITE_APP_VERSION=$NPM_VERSION 
ARG VITE_WELCOME_PATH
ARG VITE_API_TIMEOUT
ARG VITE_HONEYPOT_LOCATION_LAT
ARG VITE_HONEYPOT_LOCATION_LON
ARG VITE_HONEYPOT_NAME
ARG VITE_APP_BASE_PATH

# Trasformo gli ARG in ENV per Vite
ENV VITE_APP_TITLE=$VITE_APP_TITLE
ENV VITE_APP_VERSION=$VITE_APP_VERSION
ENV VITE_WELCOME_PATH=$VITE_WELCOME_PATH
ENV VITE_API_TIMEOUT=$VITE_API_TIMEOUT
ENV VITE_HONEYPOT_LOCATION_LAT=$VITE_HONEYPOT_LOCATION_LAT
ENV VITE_HONEYPOT_LOCATION_LON=$VITE_HONEYPOT_LOCATION_LON
ENV VITE_HONEYPOT_NAME=$VITE_HONEYPOT_NAME
ENV VITE_APP_BASE_PATH=$VITE_APP_BASE_PATH

WORKDIR /usr/app

# Copia .npmrc per l'autenticazione su Nexus (nel tarball è nella root)
COPY .npmrc /root/

# Installazione del pacchetto specifico da Nexus
RUN npm install honeypot-dashboard@$NPM_VERSION --registry=$NPM_REGISTRY_URI

# Copio i file del pacchetto nella directory di lavoro
RUN cp -fr /usr/app/node_modules/honeypot-dashboard/* /usr/app/

# Stage 2: Runtime Nginx
FROM nginx:stable-alpine
COPY --from=build /usr/app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
